### ISSUE TITLE
Platform support matrix / Native AppImage support

### ISSUE THREAD

**Issue by tpimh** [Wolfyxon/lover#3]
As I understand, currently, not all systems support all targets: for example, AppImage can only be built on Linux, Windows fused exe can be created on any platform (but macOS and Linux would need Wine to change the icon), macOS app can be created on any platform (unless they need to be signed).

A platform support matrix might be useful. Possibly, lover can also report the supported targets?

**Comment by Wolfyxon** [comment]
- [x] Add a wiki page with the matrix
- [x] Implement AppImage building without using any external tools ~~Create or find an alternative to AppImage that's buildable on Windows~~
   - [x] Verifying AppImages
   - [x] Extraction
      - [x] SquashFS extraction
      - [x] File extraction
   - [x] Packaging
      - [x] Building SquashFS
      - [x] Embedding into the AppImage

**Comment by Wolfyxon** [comment]
Here https://github.com/Wolfyxon/lover/wiki/Building

**Comment by Wolfyxon** [comment]
I'm currently figuring out the binary format of AppImages and some crates so maybe I won't have to abandon them and they'll be built and parsed natively by Lover.

I updated the TODO list.

**Comment by Wolfyxon** [comment]
All done. 
Will be available in 1.3

**Comment by Wolfyxon** [comment]
Nevermind... The crate I used ([backhand](https://github.com/wcampbell0x2a/backhand)) relies on unix modules and it doesn't compile for Windows. 

I'm working on a PR that should fix that
https://github.com/wcampbell0x2a/backhand/pull/634

**Comment by Wolfyxon** [comment]
Ok everything seems to work on Windows.
Until I finish my PR (it needs some cleanup) and it gets accepted, I'll use a submodule with my fork of backhand.
